---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggrama

<!-- badges: start -->
<!-- badges: end -->

The goal of ggrama is to make it easy to plot Ramachandran diagrams from a pdb file using ggplot2 graphics.

## Installation

You can install the development version of ggrama:

``` r
devtools::install_github("missuse/ggrama")
```

## Example

```{r example, fig.width = 4,  fig.height = 4, out.width = "50%", fig.align = 'center'}
library(ggrama)

#download a pdb file
download.file("https://files.rcsb.org/download/2ADQ.pdb1.gz",
              dest = "2ADQ.pdb1.gz")

#plot by type of Ramachandran diagrams
ggrama("2ADQ.pdb1.gz") #general type the default
ggrama("2ADQ.pdb1.gz", "pre.pro") #pre-proline, additional options are glycine and proline
```

Or plot all four types in a grid

```{r example2, fig.width = 8,  fig.height = 8}
ggrama_all("2ADQ.pdb1.gz")

```

Using contours:

```{r example3, fig.width = 8,  fig.height = 8}
ggrama_all("2ADQ.pdb1.gz",
           contour = TRUE, #contours
           smooth = TRUE, #interpolate background
           smoothing.param = "4") #coefficient of interpolation per dimension
```
